CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(25) NOT NULL,
    email VARCHAR(150) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    enabled BOOLEAN NOT NULL,
    last_seen_at TIMESTAMP(6) WITH TIME ZONE,
    avatar_url VARCHAR(255),
    stealth_mode BOOLEAN NOT NULL,
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_name VARCHAR(100),
    is_group BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS conversation_membership (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    conversation_id BIGINT NOT NULL,
    joined_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    muted BOOLEAN NOT NULL,
    notifications_on BOOLEAN NOT NULL,
    last_delivered_message_id BIGINT DEFAULT 0,
    last_read_message_id BIGINT DEFAULT 0,
    CONSTRAINT uk_conversation_membership_user_conversation UNIQUE (user_id, conversation_id),
    CONSTRAINT fk_conversation_membership_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_conversation_membership_conversation FOREIGN KEY (conversation_id) REFERENCES conversations (id)
);

CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message VARCHAR(500) NOT NULL,
    sent_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    sender_id BIGINT NOT NULL,
    conversation_id BIGINT NOT NULL,
    CONSTRAINT fk_messages_sender FOREIGN KEY (sender_id) REFERENCES users (id),
    CONSTRAINT fk_messages_conversation FOREIGN KEY (conversation_id) REFERENCES conversations (id)
);

CREATE TABLE IF NOT EXISTS attachment (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_name VARCHAR(255) NOT NULL,
    storage_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(255),
    file_size BIGINT,
    thumbnail_url VARCHAR(255),
    message_id BIGINT,
    conversation_id BIGINT,
    uploader_id BIGINT,
    CONSTRAINT uk_attachment_storage_name UNIQUE (storage_name),
    CONSTRAINT fk_attachment_message FOREIGN KEY (message_id) REFERENCES messages (id),
    CONSTRAINT fk_attachment_conversation FOREIGN KEY (conversation_id) REFERENCES conversations (id),
    CONSTRAINT fk_attachment_uploader FOREIGN KEY (uploader_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR(128) NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP(6) WITH TIME ZONE,
    replaced_by_token_hash VARCHAR(128),
    CONSTRAINT uk_refresh_tokens_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX IF NOT EXISTS idx_conversation_membership_user ON conversation_membership (user_id);
CREATE INDEX IF NOT EXISTS idx_conversation_membership_conversation ON conversation_membership (conversation_id);
CREATE INDEX IF NOT EXISTS idx_messages_conversation_sent_at ON messages (conversation_id, sent_at DESC);
CREATE INDEX IF NOT EXISTS idx_messages_conversation_id ON messages (conversation_id, id);
CREATE INDEX IF NOT EXISTS idx_messages_sender ON messages (sender_id);
CREATE INDEX IF NOT EXISTS idx_attachment_message ON attachment (message_id);
CREATE INDEX IF NOT EXISTS idx_attachment_conversation ON attachment (conversation_id);
CREATE INDEX IF NOT EXISTS idx_attachment_uploader ON attachment (uploader_id);
CREATE INDEX IF NOT EXISTS idx_refresh_token_hash ON refresh_tokens (token_hash);
CREATE INDEX IF NOT EXISTS idx_refresh_token_user ON refresh_tokens (user_id);
